version: '3.8'

services:
  web:
    build: .
    command: gunicorn app:app -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    volumes:
      - .:/app

  celery:
    build: .
    command: celery -A task worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


