name: Build and Push

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ghcr.io/janeung0215/screencap:latest
          dockerfile: ./Dockerfile
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

      - name: Deploy with Docker Compose
        run: |
          docker-compose pull
          docker-compose up -d
