   name: Build and Deploy

   on:
     push:
       branches: [master]

   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Build and push Docker image
           uses: docker/build-push-action@v2
           with:
             context: ./
             push: true
             tags: ghcr.io/janeung0215/screencap:latest

         - name: Deploy with Docker Compose
           run: |
             docker-compose pull
             docker-compose up -d
           working-directory: ./

